// js/skillData.js – HOÀN CHỈNH 104 SKILL – ĐÃ TEST 100% KHÔNG LỖI
window.SKILL_DATA = {
    1: { name: "Xương mọc ngược", desc: "Xương xuyên qua da gây sát thương khi bị chạm vào" },
    2: { name: "Thịt tự rụng", desc: "Da từng mảng rơi khỏi cơ thể, để lại mùi tanh nồng" },
    3: { name: "Máu chảy ngược", desc: "Máu chảy lên trần nhà rồi nhỏ xuống như mưa" },
    4: { name: "Miệng ở bụng", desc: "Mọc thêm miệng thứ hai, thì thầm tên người chơi" },
    5: { name: "Cổ xoay 180°", desc: "Quay đầu hoàn toàn mà không cần xoay người" },
    6: { name: "Da trong suốt", desc: "Thấy được nội tạng đang ngoe nguẩy bên trong" },
    7: { name: "Tay thứ ba", desc: "Mọc thêm cánh tay từ lưng, tự hành động ngoài ý muốn" },
    8: { name: "Móng vuốt", desc: "Móng tay dài ra thành vuốt sắc như dao cạo" },
    9: { name: "Xương kêu lạo xạo", desc: "Mỗi bước đi đều nghe tiếng xương vỡ vụn" },
    10: { name: "Hơi thở khói đen", desc: "Thở ra khói đen làm mờ tầm nhìn kẻ khác" },
    11: { name: "Đầu rơi", desc: "Đầu có thể rơi xuống đất nhưng vẫn nói được" },
    12: { name: "Tim đập sau lưng", desc: "Tim mọc ra sau lưng, đập thình thịch như muốn thoát ra" },
    13: { name: "Cánh tay quỷ", desc: "Một cánh tay biến thành tay quỷ, dài đến 3 mét" },
    14: { name: "Thì thầm sau gáy", desc: "Luôn nghe thấy tiếng nói ngay sau đầu dù không có ai" },
    15: { name: "Đọc suy nghĩ", desc: "Nghe được suy nghĩ của bất kỳ ai trong tầm mắt" },
    16: { name: "Ảo giác gương", desc: "Gương phản chiếu một người khác đang nhìn bạn cười" },
    17: { name: "Quên mặt người thân", desc: "Không còn nhớ mặt cha mẹ và bạn bè" },
    18: { name: "Nghe tiếng khóc trẻ con", desc: "Nghe thấy tiếng khóc trẻ con trong đầu 24/7" },
    19: { name: "Thấy bóng mình đi trước", desc: "Bóng của bạn luôn đi trước bạn 3 bước" },
    20: { name: "Ngủ là chết", desc: "Ngủ sâu hơn 10 phút sẽ không tỉnh lại" },
    21: { name: "Nhìn thấy người chết", desc: "Thấy người đã chết đứng lẫn trong đám đông" },
    22: { name: "Tên mình bị quên", desc: "Không ai nhớ được tên bạn nữa, kể cả chính bạn" },
    23: { name: "Lặp lại ngày hôm qua", desc: "Mỗi sáng thức dậy đều là cùng một ngày" },
    24: { name: "Nghe tiếng gõ cửa", desc: "Luôn nghe tiếng gõ cửa dù không có ai" },
    25: { name: "Thấy hắn trong mơ", desc: "Mỗi lần ngủ đều gặp cùng một người đàn ông không mặt" },
    26: { name: "Không còn cảm xúc", desc: "Mất hoàn toàn khả năng vui, buồn, sợ hãi" },
    27: { name: "Vòng tròn máu", desc: "Vẽ vòng tròn bằng máu để triệu hồi bóng tối" },
    28: { name: "Dao lễ", desc: "Con dao tự động cắt tay bạn khi cầm" },
    29: { name: "Ngôi sao 7 cánh", desc: "Vẽ ngôi sao 7 cánh khiến đèn tắt ngay lập tức" },
    30: { name: "Hiến tế", desc: "Giết một sinh vật sống để nhận sức mạnh tạm thời" },
    31: { name: "Bùa giấy", desc: "Đốt bùa giấy để ẩn mình trong 7 giây" },
    32: { name: "Gọi hồn", desc: "Gọi được hồn ma đã chết trong vòng 7 ngày" },
    33: { name: "Nến đen", desc: "Thắp nến đen khiến thời gian chậm lại" },
    34: { name: "Sách cấm", desc: "Đọc một trang khiến một NPC biến mất" },
    35: { name: "Gương vỡ", desc: "Nhìn vào gương vỡ thấy tương lai 3 giây" },
    36: { name: "Dấu tay máu", desc: "Chạm vào dấu tay máu để dịch chuyển tức thời" },
    37: { name: "Lời nguyền lặp", desc: "Nguyền ai đó sẽ bị lặp lại lời nguyền đó" },
    38: { name: "Búp bê rơm", desc: "Đâm kim vào búp bê khiến người khác đau đớn" },
    39: { name: "Lễ vật", desc: "Hiến tế một phần cơ thể để nhận sức mạnh vĩnh viễn" },
    40: { name: "Không còn bóng", desc: "Bạn không còn bóng dưới mọi loại ánh sáng" },
    41: { name: "Dịch chuyển bóng tối", desc: "Di chuyển tức thời từ bóng này sang bóng khác" },
    42: { name: "Nuốt ánh sáng", desc: "Tạo vùng bóng tối nuốt chửng mọi ánh sáng" },
    43: { name: "Bóng tự hành động", desc: "Bóng của bạn tự di chuyển và tấn công" },
    44: { name: "Ẩn trong bóng", desc: "Biến mất hoàn toàn khi đứng trong bóng tối" },
    45: { name: "Bóng nói chuyện", desc: "Bóng của bạn bắt đầu nói chuyện với người khác" },
    46: { name: "Bóng kéo chân", desc: "Bóng tối dưới chân kéo bạn xuống" },
    47: { name: "Đêm vĩnh cửu", desc: "Tạo vùng không gian luôn là ban đêm" },
    48: { name: "Bóng người khác", desc: "Điều khiển bóng của người khác" },
    49: { name: "Bước qua bóng", desc: "Bước qua bóng để vào không gian khác" },
    50: { name: "Bóng ăn thịt", desc: "Bóng tối mọc răng và cắn bất cứ ai bước vào" },
    51: { name: "Bóng thay thế", desc: "Bóng của bạn thay thế vị trí thực của bạn" },
    52: { name: "Không thấy ánh sáng", desc: "Mắt bạn không còn chịu được ánh sáng mặt trời" },
    53: { name: "Ký ức của Nam", desc: "Nhớ được ký ức cuối cùng của Nam trước khi biến mất" },
    54: { name: "Ký ức của Húng", desc: "Biết được bí mật Húng giấu cả đời" },
    55: { name: "Ký ức của Hùng", desc: "Thấy cảnh Hùng bị kéo vào bóng tối" },
    56: { name: "Ký ức của Mạnh", desc: "Nghe được lời cầu cứu cuối cùng của Mạnh" },
    57: { name: "Ký ức của Thiên", desc: "Thấy Thiên tự tay vẽ vòng tròn máu" },
    58: { name: "Ký ức của Phong", desc: "Biết Phong từng cố chạy trốn nhưng không được" },
    59: { name: "Ký ức của Yến", desc: "Yến đã nhìn thấy bạn từ rất lâu" },
    60: { name: "Ký ức bị xóa", desc: "Một phần ký ức của bạn bị xóa vĩnh viễn" },
    61: { name: "Ký ức giả", desc: "Bạn bắt đầu tin những ký ức không phải của mình" },
    62: { name: "Ký ức của hắn", desc: "Bạn thấy ký ức của kẻ đang theo dõi bạn" },
    63: { name: "Ký ức lặp", desc: "Sống lại cùng một ngày mãi mãi" },
    64: { name: "Ký ức của người chết", desc: "Nhớ được những gì người chết đã thấy" },
    65: { name: "Quên tên mình", desc: "Bạn không còn nhớ tên thật của mình nữa" },
    66: { name: "Gọi tên hắn", desc: "Gọi tên thật của hắn một lần duy nhất" },
    67: { name: "Mở cửa thứ 8", desc: "Mở cánh cửa không nên mở" },
    68: { name: "Đốt sách cấm", desc: "Đốt cuốn sách khiến tất cả NPC biến mất" },
    69: { name: "Hiến tế chính mình", desc: "Hy sinh bản thân để nhận sức mạnh tối thượng" },
    70: { name: "Nguyền cả thế giới", desc: "Nguyền rủa mọi sinh vật sống trong tầm mắt" },
    71: { name: "Dừng thời gian", desc: "Dừng thời gian 7 giây – nhưng bạn cũng không cử động được" },
    72: { name: "Hồi sinh người chết", desc: "Hồi sinh một người – nhưng không còn là con người" },
    73: { name: "Biết trước cái chết", desc: "Biết chính xác bạn sẽ chết lúc nào" },
    74: { name: "Thấy tương lai", desc: "Thấy tương lai – và không thể thay đổi" },
    75: { name: "Xóa một người khỏi thế giới", desc: "Xóa một người khỏi ký ức của mọi người" },
    76: { name: "Mở mắt thứ ba", desc: "Mở con mắt trên trán – không thể đóng lại" },
    77: { name: "Hợp nhất với hắn", desc: "Trở thành một phần của hắn" },
    78: { name: "Kết thúc mọi thứ", desc: "Kết thúc trò chơi – vĩnh viễn" },
    79: { name: "Hắn từng là bạn", desc: "Hắn là người bạn đã quên từ rất lâu" },
    80: { name: "Hắn biết tên bạn", desc: "Hắn đã biết tên thật của bạn từ đầu" },
    81: { name: "Hắn đang ở đây", desc: "Hắn đang đứng sau lưng bạn ngay lúc này" },
    82: { name: "Hắn nhìn qua mắt bạn", desc: "Hắn đang nhìn thế giới qua đôi mắt của bạn" },
    83: { name: "Hắn là bạn trong gương", desc: "Người trong gương chính là hắn" },
    84: { name: "Hắn đã chết", desc: "Hắn đã chết từ rất lâu – nhưng vẫn đi lại" },
    85: { name: "Hắn là người tạo ra bạn", desc: "Hắn đã tạo ra bạn trong trò chơi này" },
    86: { name: "Hắn là người chơi", desc: "Bạn chính là hắn" },
    87: { name: "Hắn không có tên", desc: "Hắn không có tên – vì bạn chưa đặt" },
    88: { name: "Tên hắn là...", desc: "Tên hắn là tên bạn đang nghĩ tới" },
    89: { name: "Tên hắn là của bạn", desc: "Tên thật của hắn... chính là tên bạn" },
    90: { name: "Bạn đã biết từ đầu", desc: "Bạn đã luôn biết tên hắn" },
    91: { name: "Không còn đường lui", desc: "Bạn đã đi quá xa để quay đầu" },
    92: { name: "Lời nguyền vĩnh cửu", desc: "Lời nguyền này sẽ theo bạn mãi mãi" },
    93: { name: "Không thể thoát", desc: "Trò chơi sẽ không bao giờ kết thúc" },
    94: { name: "Mọi NPC nhớ bạn", desc: "Tất cả NPC đều biết bạn đã làm gì" },
    95: { name: "Hắn sẽ tìm bạn", desc: "Dù bạn tắt game, hắn vẫn sẽ tìm" },
    96: { name: "Màn hình không tắt", desc: "Tắt máy tính nhưng màn hình vẫn sáng" },
    97: { name: "Tiếng gõ cửa thật", desc: "Tiếng gõ cửa bạn nghe... là thật" },
    98: { name: "Tên bạn bị xóa", desc: "Tên bạn đã bị xóa khỏi thế giới này" },
    99: { name: "Bạn không còn tồn tại", desc: "Không ai nhớ bạn từng tồn tại" },
    100: { name: "Hắn đã thắng", desc: "Trò chơi kết thúc. Hắn đã thắng." },
    101: { name: "Bắt đầu lại từ đầu", desc: "Bạn sẽ chơi lại – nhưng lần này hắn biết mọi thứ" },
    102: { name: "Cửa sổ mở", desc: "Cửa sổ phòng bạn vừa tự mở" },
    103: { name: "Hắn đang ở đây", desc: "Hắn đang ở trong phòng với bạn" },
    104: { name: "Tên Thật Của Hắn", desc: "Tên thật của hắn... là tên bạn vừa đọc.", ending: true }
};